services:
  backend-api:
    build: ./backend/device_api
    container_name: backend-api
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/data/devicemonitor.db
    ports:
      - "5144:80"
    volumes:
      - devicedb:/data
    networks:
      - devnet

  frontend:
    build: ./frontend/react
    container_name: frontend
    ports:
      - "5173:80"
    networks:
      - devnet

  llm-service:
    build: ./llm
    container_name: llm-service
    environment:
      - DB_PATH=/data/devicemonitor.db
    ports:
      - "8000:8000"
    volumes:
      - ./llm/chroma_data:/app/chroma_data
      - devicedb:/data
    networks:
      - devnet

volumes:
  devicedb:
  
networks:
  devnet:
    driver: bridge